// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBapnmzILLA8WhGi_ueswEUf2ch04XOUP0',
    appId: '1:1030643825993:web:f8d78b247133dd75a5ee98',
    messagingSenderId: '1030643825993',
    projectId: 'passme-73d13',
    authDomain: 'passme-73d13.firebaseapp.com',
    storageBucket: 'passme-73d13.firebasestorage.app',
    measurementId: 'G-0CRB5Z1PLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmWsW8FLa3ek0JcBewx6wkPLuL0KPSVSo',
    appId: '1:1030643825993:android:50135bfde0372a7da5ee98',
    messagingSenderId: '1030643825993',
    projectId: 'passme-73d13',
    storageBucket: 'passme-73d13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRQZ8kOgQof8iyc9O-Kaqv6mWzs9oAwWw',
    appId: '1:1030643825993:ios:f5d64fe9bb249d70a5ee98',
    messagingSenderId: '1030643825993',
    projectId: 'passme-73d13',
    storageBucket: 'passme-73d13.firebasestorage.app',
    iosBundleId: 'com.example.passMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRQZ8kOgQof8iyc9O-Kaqv6mWzs9oAwWw',
    appId: '1:1030643825993:ios:f5d64fe9bb249d70a5ee98',
    messagingSenderId: '1030643825993',
    projectId: 'passme-73d13',
    storageBucket: 'passme-73d13.firebasestorage.app',
    iosBundleId: 'com.example.passMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBapnmzILLA8WhGi_ueswEUf2ch04XOUP0',
    appId: '1:1030643825993:web:c41557d485bb5e30a5ee98',
    messagingSenderId: '1030643825993',
    projectId: 'passme-73d13',
    authDomain: 'passme-73d13.firebaseapp.com',
    storageBucket: 'passme-73d13.firebasestorage.app',
    measurementId: 'G-61T7B3F9KQ',
  );

}